// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package usecase is a generated GoMock package.
package usecase

import (
	domain "avito-test/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetTeamsByUserID mocks base method.
func (m *MockUserRepository) GetTeamsByUserID(ctx context.Context, userID string) ([]domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamsByUserID", ctx, userID)
	ret0, _ := ret[0].([]domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamsByUserID indicates an expected call of GetTeamsByUserID.
func (mr *MockUserRepositoryMockRecorder) GetTeamsByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamsByUserID", reflect.TypeOf((*MockUserRepository)(nil).GetTeamsByUserID), ctx, userID)
}

// GetUserByID mocks base method.
func (m *MockUserRepository) GetUserByID(ctx context.Context, id string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositoryMockRecorder) GetUserByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepository)(nil).GetUserByID), ctx, id)
}

// GetUsersByTeamName mocks base method.
func (m *MockUserRepository) GetUsersByTeamName(ctx context.Context, teamName string) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByTeamName", ctx, teamName)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByTeamName indicates an expected call of GetUsersByTeamName.
func (mr *MockUserRepositoryMockRecorder) GetUsersByTeamName(ctx, teamName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByTeamName", reflect.TypeOf((*MockUserRepository)(nil).GetUsersByTeamName), ctx, teamName)
}

// SaveUser mocks base method.
func (m *MockUserRepository) SaveUser(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUser indicates an expected call of SaveUser.
func (mr *MockUserRepositoryMockRecorder) SaveUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockUserRepository)(nil).SaveUser), ctx, user)
}

// UpdateUser mocks base method.
func (m *MockUserRepository) UpdateUser(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserRepositoryMockRecorder) UpdateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserRepository)(nil).UpdateUser), ctx, user)
}

// MockRequestOwnerRepository is a mock of RequestOwnerRepository interface.
type MockRequestOwnerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRequestOwnerRepositoryMockRecorder
}

// MockRequestOwnerRepositoryMockRecorder is the mock recorder for MockRequestOwnerRepository.
type MockRequestOwnerRepositoryMockRecorder struct {
	mock *MockRequestOwnerRepository
}

// NewMockRequestOwnerRepository creates a new mock instance.
func NewMockRequestOwnerRepository(ctrl *gomock.Controller) *MockRequestOwnerRepository {
	mock := &MockRequestOwnerRepository{ctrl: ctrl}
	mock.recorder = &MockRequestOwnerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestOwnerRepository) EXPECT() *MockRequestOwnerRepositoryMockRecorder {
	return m.recorder
}

// DeleteRequestOwner mocks base method.
func (m *MockRequestOwnerRepository) DeleteRequestOwner(ctx context.Context, requestOwner *domain.RequestOwner) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRequestOwner", ctx, requestOwner)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRequestOwner indicates an expected call of DeleteRequestOwner.
func (mr *MockRequestOwnerRepositoryMockRecorder) DeleteRequestOwner(ctx, requestOwner interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRequestOwner", reflect.TypeOf((*MockRequestOwnerRepository)(nil).DeleteRequestOwner), ctx, requestOwner)
}

// GetRequestsByUserID mocks base method.
func (m *MockRequestOwnerRepository) GetRequestsByUserID(ctx context.Context, userID string) ([]domain.RequestOwner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestsByUserID", ctx, userID)
	ret0, _ := ret[0].([]domain.RequestOwner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRequestsByUserID indicates an expected call of GetRequestsByUserID.
func (mr *MockRequestOwnerRepositoryMockRecorder) GetRequestsByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestsByUserID", reflect.TypeOf((*MockRequestOwnerRepository)(nil).GetRequestsByUserID), ctx, userID)
}

// GetUsersByPullRequestID mocks base method.
func (m *MockRequestOwnerRepository) GetUsersByPullRequestID(ctx context.Context, pullRequestID string) ([]domain.RequestOwner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByPullRequestID", ctx, pullRequestID)
	ret0, _ := ret[0].([]domain.RequestOwner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByPullRequestID indicates an expected call of GetUsersByPullRequestID.
func (mr *MockRequestOwnerRepositoryMockRecorder) GetUsersByPullRequestID(ctx, pullRequestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByPullRequestID", reflect.TypeOf((*MockRequestOwnerRepository)(nil).GetUsersByPullRequestID), ctx, pullRequestID)
}

// SaveRequestOwner mocks base method.
func (m *MockRequestOwnerRepository) SaveRequestOwner(ctx context.Context, request *domain.RequestOwner) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRequestOwner", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRequestOwner indicates an expected call of SaveRequestOwner.
func (mr *MockRequestOwnerRepositoryMockRecorder) SaveRequestOwner(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRequestOwner", reflect.TypeOf((*MockRequestOwnerRepository)(nil).SaveRequestOwner), ctx, request)
}

// MockTeamRepository is a mock of TeamRepository interface.
type MockTeamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryMockRecorder
}

// MockTeamRepositoryMockRecorder is the mock recorder for MockTeamRepository.
type MockTeamRepositoryMockRecorder struct {
	mock *MockTeamRepository
}

// NewMockTeamRepository creates a new mock instance.
func NewMockTeamRepository(ctrl *gomock.Controller) *MockTeamRepository {
	mock := &MockTeamRepository{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepository) EXPECT() *MockTeamRepositoryMockRecorder {
	return m.recorder
}

// GetTeamByName mocks base method.
func (m *MockTeamRepository) GetTeamByName(ctx context.Context, name string) (*domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamByName", ctx, name)
	ret0, _ := ret[0].(*domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamByName indicates an expected call of GetTeamByName.
func (mr *MockTeamRepositoryMockRecorder) GetTeamByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamByName", reflect.TypeOf((*MockTeamRepository)(nil).GetTeamByName), ctx, name)
}

// GetTeams mocks base method.
func (m *MockTeamRepository) GetTeams(ctx context.Context) ([]domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeams", ctx)
	ret0, _ := ret[0].([]domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeams indicates an expected call of GetTeams.
func (mr *MockTeamRepositoryMockRecorder) GetTeams(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeams", reflect.TypeOf((*MockTeamRepository)(nil).GetTeams), ctx)
}

// LinkUserToTeam mocks base method.
func (m *MockTeamRepository) LinkUserToTeam(ctx context.Context, team *domain.Team, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkUserToTeam", ctx, team, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkUserToTeam indicates an expected call of LinkUserToTeam.
func (mr *MockTeamRepositoryMockRecorder) LinkUserToTeam(ctx, team, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkUserToTeam", reflect.TypeOf((*MockTeamRepository)(nil).LinkUserToTeam), ctx, team, user)
}

// SaveTeam mocks base method.
func (m *MockTeamRepository) SaveTeam(ctx context.Context, team *domain.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTeam", ctx, team)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTeam indicates an expected call of SaveTeam.
func (mr *MockTeamRepositoryMockRecorder) SaveTeam(ctx, team interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTeam", reflect.TypeOf((*MockTeamRepository)(nil).SaveTeam), ctx, team)
}

// MockPullRequestRepository is a mock of PullRequestRepository interface.
type MockPullRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestRepositoryMockRecorder
}

// MockPullRequestRepositoryMockRecorder is the mock recorder for MockPullRequestRepository.
type MockPullRequestRepositoryMockRecorder struct {
	mock *MockPullRequestRepository
}

// NewMockPullRequestRepository creates a new mock instance.
func NewMockPullRequestRepository(ctrl *gomock.Controller) *MockPullRequestRepository {
	mock := &MockPullRequestRepository{ctrl: ctrl}
	mock.recorder = &MockPullRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestRepository) EXPECT() *MockPullRequestRepositoryMockRecorder {
	return m.recorder
}

// GetPullRequestByID mocks base method.
func (m *MockPullRequestRepository) GetPullRequestByID(ctx context.Context, id string) (*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequestByID", ctx, id)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequestByID indicates an expected call of GetPullRequestByID.
func (mr *MockPullRequestRepositoryMockRecorder) GetPullRequestByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequestByID", reflect.TypeOf((*MockPullRequestRepository)(nil).GetPullRequestByID), ctx, id)
}

// GetPullRequests mocks base method.
func (m *MockPullRequestRepository) GetPullRequests(ctx context.Context) ([]domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequests", ctx)
	ret0, _ := ret[0].([]domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequests indicates an expected call of GetPullRequests.
func (mr *MockPullRequestRepositoryMockRecorder) GetPullRequests(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequests", reflect.TypeOf((*MockPullRequestRepository)(nil).GetPullRequests), ctx)
}

// SavePullRequest mocks base method.
func (m *MockPullRequestRepository) SavePullRequest(ctx context.Context, pull *domain.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePullRequest", ctx, pull)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePullRequest indicates an expected call of SavePullRequest.
func (mr *MockPullRequestRepositoryMockRecorder) SavePullRequest(ctx, pull interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePullRequest", reflect.TypeOf((*MockPullRequestRepository)(nil).SavePullRequest), ctx, pull)
}

// UpdatePullRequest mocks base method.
func (m *MockPullRequestRepository) UpdatePullRequest(ctx context.Context, pull *domain.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePullRequest", ctx, pull)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePullRequest indicates an expected call of UpdatePullRequest.
func (mr *MockPullRequestRepositoryMockRecorder) UpdatePullRequest(ctx, pull interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePullRequest", reflect.TypeOf((*MockPullRequestRepository)(nil).UpdatePullRequest), ctx, pull)
}
