// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type PullRequest struct {
	Pullrequestid string         `db:"pullrequestid" json:"pullrequestid"`
	Name          sql.NullString `db:"name" json:"name"`
	Status        string         `db:"status" json:"status"`
	Createdat     time.Time      `db:"createdat" json:"createdat"`
	Mergedat      sql.NullTime   `db:"mergedat" json:"mergedat"`
}

type Team struct {
	Teamname string `db:"teamname" json:"teamname"`
}

type User struct {
	Userid   string `db:"userid" json:"userid"`
	Username string `db:"username" json:"username"`
	Isactive bool   `db:"isactive" json:"isactive"`
}

type UsersPullRequest struct {
	Pullrequestid string `db:"pullrequestid" json:"pullrequestid"`
	Userid        string `db:"userid" json:"userid"`
	Role          string `db:"role" json:"role"`
}

type UsersTeam struct {
	Teamname string `db:"teamname" json:"teamname"`
	Userid   string `db:"userid" json:"userid"`
}
